# Scrapping Google Play Review Book Cabin App

Pengumpulan data primer dilakukan melalui teknik web scraping pada platform Google Play Store terhadap aplikasi Book Cabin. Dengan menggunakan fungsi reviews_all dari library google-play-scraper, seluruh ulasan pengguna dapat diekstraksi tanpa batasan kuantitas. Proses ini dikonfigurasi pada ID paket com.spotify.music dengan filter bahasa Indonesia ('id') dan metode pengurutan terbaru (Sort.NEWEST). Pendekatan ini memastikan dataset yang diperoleh bersifat komprehensif, relevan, dan mencerminkan kondisi terkini aplikasi sebagai landasan analisis tahap berikutnya.

Install Library

In [4]:
!pip install google-play-scraper
from google_play_scraper import app, reviews_all, Sort
from datetime import datetime
import pandas as pd
import numpy as np

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 3.1 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

Informasi Aplikasi Book Cabin

In [5]:
# 1. Mengambil detail app  BookCabin
result = app(
    'com.kabinkitatop.bookcabin',
    lang='id',
    country='id'
)

# 2. Konversi Timestamp ke Format Tanggal Manusia
dt_object = datetime.fromtimestamp(result['updated'])
tanggal = dt_object.strftime('%d %B %Y, %H:%M WIB')

# 3. Menampilkan informasi spesifik terkait update
print(f"Nama Aplikasi     : {result['title']}")
print(f"Versi Terbaru     : {result['version']}")
print(f"Terakhir Diupdate  : {tanggal}")

# 4. Menampilkan dalam bentuk DataFrame
df_detail = pd.DataFrame([result])
df_detail['updated_formatted'] = tanggal
display(df_detail[['title', 'version', 'updated_formatted', 'installs']])

Nama Aplikasi     : BookCabin: Tiket Murah & Hotel
Versi Terbaru     : 6.5.3
Terakhir Diupdate  : 28 April 2026, 11:14 WIB

,title,version,updated_formatted,installs
0,BookCabin: Tiket Murah & Hotel,6.5.3,"28 April 2026, 11:14 WIB",1.000.000+

Scrapping App

In [6]:
# 1. Proses scrap
bookcabin_reviews_id = reviews_all(
    'com.kabinkitatop.bookcabin',
    sleep_milliseconds=0,
    lang='id',
    country='id',
    sort=Sort.NEWEST,
)

print(f'✅ Scraping selesai! Total ulasan terkumpul: {len(bookcabin_reviews_id):,}')

# 2. Menyimpan ke DataFrame
df_bookcabin_id = pd.DataFrame(np.array(bookcabin_reviews_id), columns=['content'])
df_bookcabin_id = df_bookcabin_id.join(pd.DataFrame(df_bookcabin_id.pop('content').tolist()))

print(f'\nJumlah baris  : {df_bookcabin_id.shape[0]:,}')
print(f'Jumlah kolom  : {df_bookcabin_id.shape[1]}')

df_bookcabin_id.head(
)

✅ Scraping selesai! Total ulasan terkumpul: 4,170

Jumlah baris  : 4,170
Jumlah kolom  : 11

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,fb60aaa9-0dfe-431a-ae8b-b8c8c0c3a937,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"applikasi terlalu banyak bug, untuk apa adanya...",1,0,6.5.3,2026-04-30 16:02:00,None,NaT,6.5.3
1,b4990d01-39f0-43ec-a231-eef344873098,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Respon Customer Care sangat mengecewakan,1,0,6.5.1,2026-04-30 05:47:15,None,NaT,6.5.1
2,76f6ed6a-1f02-4282-855f-916a3c99a0ea,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,scam. penipu. beli tiket sudah brasil malah ga...,1,0,None,2026-04-29 04:52:42,None,NaT,None
3,371dd53e-fa03-4842-9d9b-509e3c7c8f55,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"sy sudah mengajukan refund, tapi kenapa masih ...",1,0,6.5.2,2026-04-29 01:37:42,None,NaT,6.5.2
4,0625c812-0f16-435b-a11d-72e95ab9ae2d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,tolong untuk rute Berau(BEJ)-Surabaya(SUB) bel...,5,0,6.5.2,2026-04-28 12:03:09,None,NaT,6.5.2